//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaidyakovShoes
{
    using System;
    using System.Collections.Generic;
    using System.Windows;
    using System.Windows.Media;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderProduct = new HashSet<OrderProduct>();
        }
    
        public string ProductArticleNumber { get; set; }
        public string ProductName { get; set; }
        public string ProductUnit { get; set; }
        public decimal ProductCost { get; set; }
        public decimal? ProductCostWithDiscount {
            get {
                decimal? price = null;
                if (ProductDiscountAmount != null && ProductDiscountAmount > 0)
                {
                    price = ProductCost * (100 - ProductDiscountAmount) / 100;
                }
                return price; 
            }
            set { }
        }
        public Nullable<byte> ProductDiscountAmount { get; set; }
        public string ProductImporter { get; set; }
        public string ProductManufacturer { get; set; }
        public string ProductCategory { get; set; }
        public int ProductQuantityInStock { get; set; }
        public string ProductDescription { get; set; }
        public string ProductPhoto { get; set; }
        public SolidColorBrush DiscountColor
        {
            get
            {
                SolidColorBrush color = null;
                if (ProductQuantityInStock == 0)
                {
                    color = (SolidColorBrush) new BrushConverter().ConvertFromString("lightblue");
                }
                if (ProductDiscountAmount > 15)
                {
                    color = (SolidColorBrush) new BrushConverter().ConvertFromString("#2E8B57");
                }
                return color;
            }
        }
        public SolidColorBrush CostColorForOrinal
        {
            get
            {
                SolidColorBrush color = (SolidColorBrush)new BrushConverter().ConvertFromString("black");
                if (ProductDiscountAmount > 0)
                    color = (SolidColorBrush) new BrushConverter().ConvertFromString("transparent");
                return color;
            }
        }
        public SolidColorBrush CostColorForCopy
        {
            get
            {
                SolidColorBrush color = (SolidColorBrush)new BrushConverter().ConvertFromString("transparent");
                if (ProductDiscountAmount > 0)
                    color = (SolidColorBrush)new BrushConverter().ConvertFromString("red");
                return color;
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProduct { get; set; }
    }
}
